name: Backend CI/CD

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  test-lint:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Enable Yarn (via Corepack)
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn run lint

      - name: Run unit tests
        run: yarn run test

      - name: Run test coverage
        run: yarn run test:cov > coverage-summary.txt

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: coverage-summary.txt

  deploy:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    needs: test-lint
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Enable Yarn (via Corepack)
        run: corepack enable

      - name: Create .env file
        run: echo "${{ secrets.ENV_API }}" > .env

      - name: Build and deploy with Docker
        run: |
          docker compose down || true
          docker compose up -d --build

      - name: Show running containers
        run: docker ps
